### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by SynapseScribe** [Timemaster111/githubwebhook#4]

**Comment by Kitsuneko111** [comment]
Hi, yes this should still be working, I can test it for you shortly if you like

**Comment by Kitsuneko111** [comment]
Yes this is still working. There was an amount of downtime yesterday just before you sent this message but I am unsure what caused this, sorry for the inconvenience.
Thank you for using my service :)

**Comment by SynapseScribe** [comment]
Yes it works now. Thank you.

**Comment by SynapseScribe** [comment]
again not working
